version: '3.9'

services:
    postgres:
        container_name: ${POSTGRES_CONTAINER_NAME}
        image: 'postgres:alpine'
        environment:
            - POSTGRES_DB=${POSTGRES_DATABASE}
            - POSTGRES_USER=${POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_PORT=${POSTGRES_PORT}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes:
            - ./data/postgres:/var/lib/postgresql/data

    pgAdmin:
        container_name: ${PGADMIN_CONTAINER_NAME}
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - '${PGADMIN_PORT}:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        restart: unless-stopped
